---
- name: Install build dependencies
  apt:
    update_cache: yes
    pkg:
    - gawk
    - wget
    - git-core
#    - diffstat
#    - unzip
#    - texinfo
#    - gcc-multilib
    - build-essential
#    - chrpath
#    - socat
#    - cpio
    - python3
    - python3-pip
    - python3-pexpect
#    - xz-utils
    - debianutils
#    - iputils-ping
    - python3-git
    - python3-jinja2
#    - libegl1-mesa
#    - libsdl1.2-dev
#    - pylint3

- name: Install buildbot_worker
  pip:
    name: "buildbot-worker"
    executable: pip3
    state: present

- name: Create /etc/default/buildbot-worker
  template:
    src: Debian.default.j2
    dest: /etc/default/buildbot-worker
  when: 1 == 0

- name: Enable buildbot_worker_service
  service:
    name: "{{ buildbot_worker_service }}"
    enabled: yes
